#!/bin/bash

set -e

# 声明信息
echo "本脚本由道行歌/JoeY制作"
echo "酒馆是一个使用各种AI的工具，用户需自备能使用AI的代理、API或曲奇。如需咨询酒馆如何连接claude等问题，可在必要时查看爱发电主页联系作者"
echo "爱发电地址：https://afdian.net/a/JoeY400请理解，作者的时间也非常宝贵。"
echo "脚本执行中..."

# 检查网络状况
echo "检查网络连接..."
ping -c 1 google.com > /dev/null 2>&1 || { echo "网络连接失败，请检查你的网络设置。梯子不行就换，信号不行就wifi,5G互换"; exit 1; }

# 更新软件包信息
echo "更新软件包信息..."
apt-get update -y || {
    echo "更新软件包信息失败，尝试选择一个软件源..."
    termux-change-repo
    apt-get update -y || { echo "无法更新软件包信息，请检查你的网络连接或手动选择一个软件源。"; exit 1; }
}

# 升级所有软件包，自动接受新的配置文件
echo "升级软件包..."
apt-get upgrade -y -o Dpkg::Options::="--force-confnew"

# 清理可能存在的无用软件包
echo "清理无用软件包..."
apt-get autoclean -y
apt-get clean -y

# 检查Git是否已安装
if ! command -v git &> /dev/null; then
    echo "安装Git..."
    pkg install git -y
else
    echo "Git已安装，跳过此步骤."
fi

# 克隆SillyTavern仓库
REPO_URL="https://github.com/SillyTavern/SillyTavern.git"
echo "克隆SillyTavern仓库: $REPO_URL"
git clone $REPO_URL || { echo "无法克隆仓库,清除Termux应用数据后再次运行脚本"; exit 1; }

# 进入SillyTavern目录并安装node.js和依赖项
echo "进入SillyTavern目录..."
cd SillyTavern

echo "安装node.js和依赖项..."
if ! command -v node &> /dev/null; then
    pkg install nodejs -y
else
    echo "Node.js已安装，跳过此步骤."
fi
npm install || { echo "安装依赖失败"; exit 1; }

# 运行SillyTavern
echo "运行SillyTavern..."
./start.sh || bash start.sh

echo "SillyTavern已经启动！"
echo "感谢使用"
